# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.7.4-buster-node-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/AIP_BackEnd

    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init

      # Download and cache dependencies
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - restore_cache:
          name: restore pipenv cache
          keys:
            - deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - restore_cache:
          name: restore yarn cache
          keys:
            - yarn-package-{{ checksum "frontend/yarn.lock" }}

      - run:
          name: install dependencies
          command: |
            sudo apt-get install libgmp3-dev libmpfr-dev libmpc-dev
            sudo pip install pipenv
            pipenv install
            pipenv install --dev

      - run:
          name: build frontend
          command: |
            yarn global add @vue/cli @vue/cli-service @vue/cli-plugin-unit-jest
            export PATH="$PATH:$(yarn global bin)"
            cd frontend && yarn install && yarn build --frozen-lockfile

      - save_cache:
          name: save python cache
          paths:
            - ".env"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.7/site-packages"
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

      - save_cache:
          paths:
            - ~/.cache/yarn
            - frontend/node_modules
          key: yarn-package-{{ checksum "frontend/yarn.lock" }}
          name: save yarn cache

      # run tests!
      # this example uses Django's built-in test-runner
      # other common Python testing frameworks include pytest and nose
      # https://pytest.org
      # https://nose.readthedocs.io
      # - run:
      #     name: run tests
      #     command: |
      #       pipenv run python manage.py test --parallel
      #       cd frontend && yarn run test:unit
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: build docker image
          command: |
            docker build -t felinae98/tapes-aip .
            echo $DOCKER_PASS | docker login -u $DOCKER_LOGIN --password-stdin
            docker push felinae98/tapes-aip
      - store_artifacts:
          path: test-reports
          destination: test-reports