# Generated by Django 2.2.3 on 2019-07-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aipsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publickey',
            name='semaster',
            field=models.CharField(max_length=20, verbose_name='学期'),
        ),
    ]
