# Generated by Django 2.2.3 on 2019-07-12 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aipsite', '0002_auto_20190712_0636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aipuser',
            old_name='classno',
            new_name='teaching_class',
        ),
    ]
