# Generated by Django 2.2.3 on 2019-07-11 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aipsite', '0002_auto_20190711_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aipuser',
            name='classno',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='aipsite.PublicKey'),
        ),
    ]
