# Generated by Django 2.2.3 on 2019-07-14 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aipsite', '0003_auto_20190712_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publickey',
            old_name='semaster',
            new_name='semester',
        ),
    ]
