# Generated by Django 2.2.3 on 2019-07-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aipsite', '0004_auto_20190714_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publickey',
            name='a',
            field=models.CharField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='publickey',
            name='b',
            field=models.CharField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='publickey',
            name='c',
            field=models.CharField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='publickey',
            name='g',
            field=models.CharField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='publickey',
            name='h',
            field=models.CharField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='publickey',
            name='n',
            field=models.CharField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='publickey',
            name='p',
            field=models.CharField(blank=True, max_length=1500),
        ),
    ]
